site_name: CS479 Machine Learning for 3D Data (KAIST, Fall 2023)

theme:
  name: material
  icon:
    logo: material/cube-outline
  features:
    - navigation.tabs
    - navigation.tabs.sticky

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - footnotes
  - meta
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - tables

plugins:
  - macros

copyright: Copyright &copy; 2023 Minhyuk Sung

nav:
  - Home: index.md
  - Programming Assignments: programming-assignments.md
  - Project:
    - Project Team Matching: project-team-matching.md
    - Project Proposal: project-proposal.md
    - Project Tracks: project-tracks.md
    - Project Mockup: project-mockup.md
    - Project Pitch Video: project-pitch-video.md

extra:
  analytics:
    provider: google
    property: G-S3GEPQ874N
  links:
    paper_list: https://docs.google.com/spreadsheets/d/1i-C6Ao4mrXnVqj0AKnTfS0AB6hd8SpEuB3JI1JZgKbI/edit?usp=sharing
    lec01: https://kaistackr-my.sharepoint.com/:b:/g/personal/mhsung_kaist_ac_kr/EXPl933tZ9BItoZdMeJyuHwByUNJLCP1nNWdZ-muOxPadA?e=XcxmSR
    lec02: https://kaistackr-my.sharepoint.com/:b:/g/personal/mhsung_kaist_ac_kr/EROv07NTwj9Fonaz3CZUmfMBHsP6VManKqHwAeGTdXuwdQ?e=slbVJr
    lec03: https://kaistackr-my.sharepoint.com/:b:/g/personal/mhsung_kaist_ac_kr/EQiHg0GE8qZDuji_XAfGgS0BoA6aXZstPsDTAYDs5pNLHw?e=peXQXK
    lec04: https://kaistackr-my.sharepoint.com/:b:/g/personal/mhsung_kaist_ac_kr/EU7Gy2aM4JZEmaD-hv0wffkBX6TpYaXk5Jq6KTNpVdY4bA?e=MalZFJ
    lec05: https://kaistackr-my.sharepoint.com/:b:/g/personal/mhsung_kaist_ac_kr/EcUsLOLibAdGpqjpI1tIaUEBAPaSOgH7_vH5D6Zvu7b5eA?e=B4V7bG
    lec06: https://kaistackr-my.sharepoint.com/:b:/g/personal/mhsung_kaist_ac_kr/EQc9ZJ0sVtVBv4gw2v3lUMwBqow1TtD0VM8xesHmzFjnxg?e=nN2GN3
    lec07: https://kaistackr-my.sharepoint.com/:b:/g/personal/mhsung_kaist_ac_kr/ETLaY6j9B69Fn6kgMizYJisBgsZf6nqPIyWSMWxRfMrBeg?e=JurRje
    rec01: https://youtu.be/ghGk3HcxUgg
    rec02: https://youtu.be/933wv8i3QKU
    rec03: https://youtu.be/i04fhF9fOdM
    rec04: https://youtu.be/p3eWGEUYkwM
    rec05: https://youtu.be/kyFX7T_Wma8
    rec06: https://youtu.be/_7z9YWSF0QE
    rec07: https://youtu.be/psvsLo8xcjI
