site_name: CS479 Machine Learning for 3D Data (KAIST, Fall 2023)

theme:
  name: material
  icon:
    logo: material/cube-outline
  features:
    - navigation.tabs
    - navigation.tabs.sticky

extra:
  analytics:
    provider: google
    property: G-S3GEPQ874N

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - footnotes
  - meta
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - tables

plugins:
  - macros

extra:
  links:

copyright: Copyright &copy; 2023 Minhyuk Sung

nav:
  - Home: index.md
  - Programming Assignments: programming-assignments.md
  - Project:
    - Project Team Matching: project-team-matching.md
    - Project Proposal: project-proposal.md
    - Project Tracks: project-tracks.md
    - Project Mockup: project-mockup.md
    - Project Pitch Video: project-pitch-video.md

extra:
  links:
    paper_list: https://docs.google.com/spreadsheets/d/1i-C6Ao4mrXnVqj0AKnTfS0AB6hd8SpEuB3JI1JZgKbI/edit?usp=sharing
